# <b>Fondamenti di Analisi Dati</b> - a.a. 2020/2021

## 2 <b>NumPy</b>

<b>NumPy</b> è la libreria di riferimento di <b>SciPy</b> per il calcolo scientifico. Il cuore della libreria è costituito dai <b>numpy array</b> che permettono di gestire agevolmente operazioni tra vettori e matrici. Gli array di Python sono in generale tensori, ovvero strutture numeriche dal numero di dimensioni variabili, che possono dunque essere array monodimensionali, matrici bidimensionali, o
strutture a più dimensioni (es. cuboidi 10 x 10 x 10). Per utilizzare gli array di numpy, dobbiamo prima importare il pacchetto
numpy.

In [1]:
import numpy as np #la notazione "as" ci permette di referenziare il namespace numpy semplicemente con np in futuro

### 2.1 NumPy Arrays

Un array multidimensionale di numpy può essere definito a partire da una lista di liste.

In [2]:
l = [[1,2,3],[4,5,2],[1,8,3]] #una lista contenente tre liste
print("List of lists:", l, end="\n\n") #viene visualizzata così come l'abbiamo definita

a = np.array(l) #costruisco un array di numpy a partire dalla lista di liste

print("Numpy array:\n", a, end="\n\n") #ogni lista interna viene identificata come una riga di unamatrice bidimensionale

print("Numpy array from tuple:\n",np.array(((1,2,3),(4,5,6)))) #posso creare numpy array anche da tuple

List of lists: [[1, 2, 3], [4, 5, 2], [1, 8, 3]]

Numpy array:
 [[1 2 3]
 [4 5 2]
 [1 8 3]]

Numpy array from tuple:
 [[1 2 3]
 [4 5 6]]


Ogni array di numpy ha una proprietà <i>shape</i> che ci permette di determinare il numero di dimensioni della struttura.

In [3]:
print(a.shape) #si tratta di una matrice 3 x 3

(3, 3)


In [4]:
array = np.array([1,2,3,4])
matrice = np.array([[1,2,3,4],[5,4,2,3],[7,5,3,2],[0,2,3,1]])
tensore = np.array([[[1,2,3,4],['a','b','c','d']],[[5,4,2,3],['a','b','c','d']],[[7,5,3,2],['a','b','c','d']],[[0,2,3,1],['a','b','c','d']]])
print('Array:',array, array.shape, "\n") #array monodimensionale, avrà una sola dimensione
print('Matrix:\n',matrice, matrice.shape, "\n")
print('Tensor:\n',tensore, tensore.shape) #tensore: avrà tre dimensioni

Array: [1 2 3 4] (4,) 

Matrix:
 [[1 2 3 4]
 [5 4 2 3]
 [7 5 3 2]
 [0 2 3 1]] (4, 4) 

Tensor:
 [[['1' '2' '3' '4']
  ['a' 'b' 'c' 'd']]

 [['5' '4' '2' '3']
  ['a' 'b' 'c' 'd']]

 [['7' '5' '3' '2']
  ['a' 'b' 'c' 'd']]

 [['0' '2' '3' '1']
  ['a' 'b' 'c' 'd']]] (4, 2, 4)


Alcune operazioni tra numpy array:

In [5]:
a1 = np.array([1,2,3,4])
a2 = np.array([4,3,8,1])
print("Sum:",a1+a2) #somma tra vettori
print("Elementwise multiplication:",a1*a2) #moltiplicazione tra elementi corrispondenti
print("Power of two:",a1**2) #quadrato degli elementi
print("Elementwise power:",a1**a2) #elevamento a potenza elemento per elemento
print("Dot product:",a1.dot(a2)) #prodotto interno
print("Minimum:",a1.min()) #minimo dell'array
print("Maximum:",a1.max()) #massimo dell'array
print("Sum:",a2.sum()) #somma di tutti i valori dell'array
print("Product:",a2.prod()) #prodotto di tutti i valori dell'array
print("Mean:",a1.mean()) #media di tutti i valori dell'array

Sum: [ 5  5 11  5]
Elementwise multiplication: [ 4  6 24  4]
Power of two: [ 1  4  9 16]
Elementwise power: [   1    8 6561    4]
Dot product: 38
Minimum: 1
Maximum: 4
Sum: 16
Product: 96
Mean: 2.5


Operazioni tra matrici:

In [6]:
m1 = np.array([[1,2,3,4],[5,4,2,3],[7,5,3,2],[0,2,3,1]])
m2 = np.array([[8,2,1,4],[0,4,6,1],[4,4,2,0],[0,1,8,6]])
print("m1:\n",m1,"\nm2:\n",m2)
print("Sum:\n",m1+m2) #somma tra matrici
print("Elementwise product:\n",m1*m2) #prodotto elemento per elemento
print("Power of two:\n",m1**2) #quadrato degli elementi
print("Elementwise power:\n",m1**m2) #elevamento a potenza elemento per elemento
print("Matrix multiplication:\n",m1.dot(m2)) #prodotto matriciale
print("Minimum:",m1.min()) #minimo
print("Maximum:",m1.max()) #massimo
print("Minimum along columns:",m1.min(0)) #minimo per colonne
print("Minimum along rows:",m1.min(1)) #minimo per righe
print("Sum:",m1.sum()) #somma dei valori
print("Mean:",m1.mean()) #valore medio
print("Diagonal:",m1.diagonal()) #diagonale principale della matrice
print("Transposed:\n",m1.T) #matrice trasposta

m1:
 [[1 2 3 4]
 [5 4 2 3]
 [7 5 3 2]
 [0 2 3 1]] 
m2:
 [[8 2 1 4]
 [0 4 6 1]
 [4 4 2 0]
 [0 1 8 6]]
Sum:
 [[ 9  4  4  8]
 [ 5  8  8  4]
 [11  9  5  2]
 [ 0  3 11  7]]
Elementwise product:
 [[ 8  4  3 16]
 [ 0 16 12  3]
 [28 20  6  0]
 [ 0  2 24  6]]
Power of two:
 [[ 1  4  9 16]
 [25 16  4  9]
 [49 25  9  4]
 [ 0  4  9  1]]
Elementwise power:
 [[   1    4    3  256]
 [   1  256   64    3]
 [2401  625    9    1]
 [   1    2 6561    1]]
Matrix multiplication:
 [[20 26 51 30]
 [48 37 57 42]
 [68 48 59 45]
 [12 21 26  8]]
Minimum: 0
Maximum: 7
Minimum along columns: [0 2 2 1]
Minimum along rows: [1 2 2 0]
Sum: 47
Mean: 2.9375
Diagonal: [1 4 3 1]
Transposed:
 [[1 5 7 0]
 [2 4 5 2]
 [3 2 3 3]
 [4 3 2 1]]


### 2.2 Linspace, Arange, Zeros, Ones, Eye e Random

Le funzioni <b>linspace</b>, <b>arange</b>, <b>zeros</b>, <b>ones</b>, <b>eye</b> e <b>random</b> di numpy sono utili a generare array numerici.<br>
In particolare <b>linspace</b> permette di generare una sequenza di <b>n</b> numeri equispaziati che vanno da un valore minimo a un valore massimo.

In [7]:
a=np.linspace(10,20,5) # genera 5 valori equispaziati che vanno da 10 a 20
print(a)

[10.  12.5 15.  17.5 20. ]


<b>arange</b> è molto simile a range, ma restituisce direttamente un array di numpy:

In [8]:
print(np.arange(10)) #numeri da 0 a 9
print(np.arange(1,6)) #numeri da 1 a 5
print(np.arange(0,7,2)) #numeri pari da 0 a 6

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[0 2 4 6]


In [9]:
print(list(range(10)))
print(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


Possiamo creare array di forme arbitrarie, contenenti zero o uno, attraverso <b>zeros</b> e <b>ones</b>.

In [10]:
print(np.zeros((3,4)))#zeros e ones prendono come parametro una tupla contenente le dimensioni desiderate
print(np.ones((2,1)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1.]
 [1.]]


La funzione <b>eye</b> permette di creare una matrice identità.

In [11]:
print(np.eye(3))
print(np.eye(5))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


NumPy possiede un sottomodulo <b>random</b> per generare numeri casuali attraverso diversi metodi.
Possiamo costruire, per esempio, un numpy array di valori casuali (distribuzione uniforme) tra 0 e 1 (zero incluso, uno escluso) tramite <b>rand</b>.

In [12]:
print(np.random.rand(5)) #un array con 5 valori casuali tra 0 e 1
print(np.random.rand(3,2)) #una matrice 3x2 di valori casuali tra 0 e 1

[0.3993123  0.70523959 0.42138811 0.02090879 0.92875614]
[[0.68040171 0.88780473]
 [0.78882549 0.63137248]
 [0.70813349 0.8428989 ]]


Possiamo invece generare un array di valori casuali distribuiti in maniera normale (Gaussiana) con randn.

In [13]:
print(np.random.randn(5,2))

[[-0.4295706  -1.95041137]
 [ 2.29769345 -0.21760275]
 [-0.4020634   0.08450852]
 [-0.43217539  0.24033547]
 [-0.08637498 -0.44869471]]


Possiamo generare numeri interi compresi tra un minimo (incluso) e un massimo (escluso) usando <b>randint</b>.

In [14]:
print(np.random.randint(0,50,3))#tre valori compresi tra 0 e 50 (escluso)
print(np.random.randint(0,50,(2,3)))#matrice 2x3 di valori interi casuali tra 0 e 50 (escluso)

[35 14  0]
[[12 28 10]
 [ 7 46  9]]


Per generare valori casuali in maniera replicabile è possibile specificare un <b>seed</b>.

In [20]:
np.random.seed(12345)
print(np.random.rand(5))

[0.92961609 0.31637555 0.18391881 0.20456028 0.56772503]


Specificando lo stesso seed otterremo gli stessi valori.

In [23]:
np.random.seed(123)
print(np.random.rand(5))

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


### 2.3 max, min, sum, argmax, argmin

In [24]:
m = np.array([[-1,3,7],[6,2,5],[4,-3,-9],[15,21,-14]])
print(m,"\n")
print(m.max(0),"\n")# massimi per colonne
print(m.max(1),"\n")# massimi per righe
print(m.min(0),"\n")# minimi per colonne
print(m.min(1),"\n")# minimi per righe
print(m.sum(0),"\n")# somma per colonne
print(m.sum(1),"\n")# somma per righe
print(m.max())# massimo globale
print(m.min())# minimo globale
print(m.sum())# somma globale

[[ -1   3   7]
 [  6   2   5]
 [  4  -3  -9]
 [ 15  21 -14]] 

[15 21  7] 

[ 7  6  4 21] 

[ -1  -3 -14] 

[ -1   2  -9 -14] 

[ 24  23 -11] 

[ 9 13 -8 22] 

21
-14
36


È possibile ottenere gli indici in corrispondenza dei quali si hanno massimi e minimi usando <b>argmax</b> e <b>argmin</b>.

In [25]:
print(m.argmax(0)) #indice colonna del valore massimo
print(m.argmax(1)) #indice riga del valore massimo
print(m.argmin(0)) #indice colonna del valore minimo
print(m.argmin(1)) #indice riga del valore minimo

[3 3 0]
[2 0 0 1]
[0 2 3]
[0 1 2 2]


### 2.4 Indicizzazione e Slicing

Gli array di numpy possono essere indicizzati in maniera simile a quanto avviene per le liste.

In [26]:
arr = np.array([0,1,2,3,4,5])
print("arr[0] ->",arr[0]) #primo elemento dell'array (indice 0)
print("arr[:3] ->",arr[:3]) #primi tre elementi (da 0 a 3 escluso)
print("arr[1:4:2] ->",arr[1:4:2]) #dall'elemento con indice 1 a quello con indice 4 (escluso) a step 2

arr[0] -> 0
arr[:3] -> [0 1 2]
arr[1:4:2] -> [1 3]


Quando si indicizza un array a più di una dimensioni con un unico indice, viene in automatico indicizzata la prima dimensione.
<br>Vediamo qualche esempio con le matrici bidimensionali:

In [27]:
mat = np.array(([2,6,7,2],[3,7,3,1],[4,9,8,9]))
print("Matrice:\n",mat,mat.shape) #matrice 3 x 4
print("mat[0] ->",mat[0]) #una matrice è una collezione di righe, per cui mat[0] restituisce la prima riga
print("mat[-1] ->",mat[-1]) #ultima riga
print("mat[::2] ->",mat[::2]) #righe dispari (una riga sì e una no)

Matrice:
 [[2 6 7 2]
 [3 7 3 1]
 [4 9 8 9]] (3, 4)
mat[0] -> [2 6 7 2]
mat[-1] -> [4 9 8 9]
mat[::2] -> [[2 6 7 2]
 [4 9 8 9]]


Vediamo qualche esempio con tensori a più dimensioni.

In [ ]:
tens = np.array(([[1,5,2,7],[2,7,3,2],[1,5,2,1]],
                 [[3,4,2,6],[2,3,2,2],[1,1,4,5]],
                 [[2,4,6,8],[3,6,9,0],[1,2,3,4]]))
print("Tensore:\n",tens,tens.shape,"\n") #tensore 2x3x4
print("tens[0] ->",tens[0],"\n") #prima matrice 3x4
print("tens[-1] ->",tens[-1],"\n") #ultima matrice 3x4
print("tens[::2] ->",tens[::2]) #matrici dispari

L'indicizzazione può proseguire attraverso le altre dimensioni specificando un ulteriore indice in parentesi quadre o separando i
vari indici con la virgola.

In [ ]:
mat = np.array(([1,5,2,7],[2,7,3,2],[3,4,2,1]))
print("Matrice:\n",mat,mat.shape) #matrice 3 x 4
print("mat[2][1] ->",mat[2][1]) #terza riga, seconda colonna
print("mat[0,0] ->",mat[0,0]) #prima riga, prima colonna (notazione più compatta)
print("mat[0] -> ",mat[0]) #restituisce l'intera prima riga della matrice
print("mat[:,0] -> ",mat[:,0]) #restituisce la prima colonna della matrice.
#I due punti ":" significano "lascia tutto inalterato lungo questa dimensione"
print("mat[0,:] ->",mat[0,:]) #notazione alternativa per ottenere la prima riga del la matrice
print("mat[0:2,:] ->\n",mat[0:2,:]) #prime due righe
print("mat[:,0:2] ->\n",mat[:,0:2]) #prime due colonne
print("mat[-1] ->",mat[-1]) #ultima riga

Caso di tensori a più dimensioni:

In [ ]:
mat=np.array([[[1,2,3,4],['a','b','c','d']],
              [[5,4,2,3],['a','b','c','d']],
              [[7,5,3,2],['a','b','c','d']],
              [[0,2,3,1],['a','b','c','d']]])
print(mat,"\n")
print("mat[:,:,0] ->\n", mat[:,:,0],"\n") #matrice contenuta nel "primo canale" del tensore
print("mat[:,:,1] ->\n",mat[:,:,1],"\n") #matrice contenuta nel "secondo canale" del tensore
print("mat[...,0] ->\n", mat[...,0],"\n") #matrice contenuta nel "primo canale" del tensore (notazione alternativa)
print("mat[...,1] ->\n",mat[...,1],"\n") #matrice contenuta nel "secondo canale" del tensore (notazione alternativa)
#la notazione "..." serve a dire "lascia tutto invariato lungo le dimensioni omesse"

In genere, quando da un array si estrae un sottoinsieme di dati si parla di <b>slicing</b> (affettare).

### 2.4.1 Indicizzazione e Slicing Logici

In numpy è inoltre possibile indicizzare gli array in maniera "logica", ovvero passando come indici un array di valori booleani. Ad
esempio, se vogliamo selezionare il primo e il terzo valore di un array, dobbiamo passare come indici l'array [True, False,
True].

In [ ]:
x = np.array([0,1,2])
print(x[np.array([True,False,True])]) #per selezionare solo 0 e 2
print(x[np.array([False,True,False])]) #per selezionare solo 1

L'indicizzazione logica è molto utile se combinata alla possibilità di costruire array logici <i>on the fly</i> specificando una condizione che gli elementi di un array possono o non possono soddisfare.

In [ ]:
x = np.arange(10)
print(x)
print(x>2) #genera un array di valori booleani che conterrà True in presenza dei valori di x che verificano la condizione x>2
print(x==3) #True solo in presenza del valore 3

Unendo questi due principi è possibile selezionare solo alcuni valori da un array sulla base di una condizione.

In [ ]:
x = np.arange(10)
print(x[x%2==0]) #seleziona i valori pari
print(x[x%2!=0]) #seleziona i valori dispari
print(x[x>2]) #seleziona i valori maggiori di 2

### 2.5 Reshape

In alcuni casi può essere utile cambiare la "shape" di una matrice. Ad esempio, una matrice 3x2 può essere modificata
riarrangiando gli elementi in modo da ottenere una matrice 2x3, una matrice 1x6 o una matrice 6x1. Ciò si può fare mediante il
metodo <b>reshape</b>.

In [ ]:
mat = np.array([[1,2],[3,4],[5,6]])
print(mat,"\n")
print(mat.reshape(2,3),"\n")
print(mat.reshape(1,6),"\n")
print(mat.reshape(6,1),"\n") #matrice 6 x 1
print(mat.reshape(6),"\n") #vettore unidimensionale
print(mat.ravel())#equivalente al precedente, ma aparametrico

Notiamo che, se leggiamo per righe (da sinistra verso destra, dall'alto verso il basso), l'ordine degli elementi resta immutato.
Possiamo anche lasciare che numpy clacoli una delle dimensioni sostituendola con <b>-1</b>.

In [ ]:
print(mat.reshape(2,-1))
print(mat.reshape(-1,6))

Reshape può prendere in input le singole dimensioni o una tupla contenente la shape. È quindi possibile passare come parametro la shape di un'altra matrice.

In [ ]:
mat1 = np.random.rand(3,2)
mat2 = np.random.rand(2,3)
print(mat2.reshape(mat1.shape)) #diamo a mat2 la stessa shape di mat1

### 2.6 Composizione di array mediante <i>concatenate</i> e <i>stack</i>

NumPy permette di unire diversi array mediante due funzioni principale: <b>concatenate</b> e <b>stack</b>.
<br>La funzione <b>concatenate</b> prende in input una lista (o tupla) di array e permette di concatenarli lungo una dimensione esistente
specificata (axis), che di default è pari a 0 (concatenazione per righe).

In [ ]:
a=np.arange(9).reshape(3,3)
print(a,a.shape,"\n")
cat=np.concatenate([a,a])
print(cat,cat.shape,"\n")
cat2=np.concatenate([a,a,a])
print(cat2,cat2.shape)

È possibile concatenare array su una dimensione diversa specificandola mediante il parametro <i>axis</i>.

In [ ]:
a=np.arange(9).reshape(3,3)
print(a,a.shape,"\n")
cat=np.concatenate([a,a], axis=1) #concatenazione per colonne
print(cat,cat.shape,"\n")
cat2=np.concatenate([a,a,a], axis=1) #concatenazione per colonne
print(cat2,cat2.shape)

<b>N.B.:</b> affinché la concatenazione sia compatibile, gli array della lista devono avere lo stesso numero di dimensioni lungo quelle che <u>non vengono concatenate</u>.

In [ ]:
print(cat.shape,a.shape,"\n") #concatenazione lungo l'asse 0, le dimensioni lungo gli altri assi devono essere uguali
print(cat,"\n\n",a,"\n")
print(np.concatenate([cat,a], axis=1)) #concatenazione per righe (nel nostro caso uguali a 3 sia per cat che per a)

In [ ]:
np.concatenate([cat,a], axis=0) #concatenazione per colonne (6 per cat e 3 per a: errore!)

La funzione <b>stack</b>, a differenza di concatenate permette di concatenare array lungo una nuova dimensione. Si confrontino
gli output delle due funzioni.

In [ ]:
cat=np.concatenate([a,a])
print(cat,cat.shape,"\n")
stack=np.stack([a,a])
print(stack,stack.shape)

Nel caso di stack, gli array sono stati concatenati lungo una nuova dimensione. E' possibile specificare dimensioni alternative
come nel caso di concatenate.

In [ ]:
stack=np.stack([a,a],axis=1)
print(stack,stack.shape)

In questo caso gli array sono stati concatenati lungo la seconda dimensione.

In [ ]:
stack=np.stack([a,a],axis=2)
print(stack,stack.shape)

In questo caso gli array sono stati concatenati lungo l'ultima dimensione.

### 2.7 Tipi

Ogni array di numpy ha il suo tipo (si veda <a href="https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html" target="_blank">https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html</a> per la lista di tipi
supportati). Possiamo vedere il tipo di un array ispezionando la proprietà <b>dtype</b>.

In [ ]:
print(mat1)
print(mat1.dtype)

Possiamo specificare il tipo in fase di costruzione dell'array.

In [ ]:
mat = np.array([[1,2,3],[4,5,6]],int)
print(mat.dtype)

Possiamo inoltre cambiare il tipo di un array utilizzando <b>astype</b>.

In [ ]:
m =  np.array([[1.5,2.3,3.4],[4.6,5,6.2]],float)
print(m)
print(m.astype(int))

### 2.8 Gestione della memoria in NumPy

NumPy gestisce la memoria in maniera dinamica per questioni di efficienza. Pertanto, un assegnamento o una operazione di
slicing in genere <b>non creano una nuova copia dei dati</b>. Si consideri ad esempio questo codice:

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a,"\n")
b=a[0,0:2]
print(b)

L'operazione di slicing <code>b=a[0,0:2]</code> ha solo permesso di ottenere una nuova "vista" di una parte di <code>a</code>, ma i dati non sono stati replicati in memoria. Pertanto, se modifichiamo un elemento di <code>b</code>, la modifica verrà applicata in realtà ad <code>a</code>.

In [ ]:
b[0]=-1
print(b,"\n")
print(a)

Per evitare questo genere di comportamenti, è possibile utilizzare il metodo <b>copy</b> che forza numpy a creare una nuova copia
dei dati.

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a,"\n")
b=a[0,0:2].copy()
print(b,"\n")
b[0]=-1
print(b,"\n")
print(a)
#in questo caso a resta inalterato alla modifica di b

### 2.9 Broadcasting

NumPy gestisce in maniera intelligente le operazioni tra array che presentano shape diverse sotto determinate condizioni.
Vediamo un esempio pratico: supponiamo di avere una matrice 2x3 e un array 1x3:

In [ ]:
mat=np.array([[1,2,3],[4,5,6]],dtype=np.float)
arr=np.array([2,3,8])
print(mat,mat.shape,"\n")
print(arr,arr.shape)

Supponiamo adesso di voler dividere, elemento per elemento, tutti i valori di ogni riga della matrice per i valori dell'array.
Possiamo eseguire l'operazione richiesta mediante un ciclo for:

In [ ]:
mat2=mat.copy() #copia il contenuto della matrice per non sovrascriverla
for i in range(mat2.shape[0]): #indicizza le righe
    mat2[i]=mat2[i]/arr
print(mat2)

Se non volessimo utilizzare cicli for, potremmo replicare <code>arr</code> in modo da ottenere una matrice e poi effettuare una semplice
divisione elemento per elemento.

In [ ]:
arr2=np.stack([arr,arr])
print(arr2,"\n")
print(mat/arr2)

Lo stesso risultato si può ottenere semplicemente chiedendo a numpy di dividere <code>mat</code> per <code>arr</code>:

In [ ]:
print(mat/arr)

Ciò avviene in quanto numpy confronta le dimensioni dei due operandi (2x3 e 1x3) e adatta l'operando con shape più
piccola a quello con shape più grande, replicandone gli elementi lungo la dimensione unitaria (la prima). Il broadcasting in pratica
generalizza le operazioni tra scalari e vettori/matrici.

In generale, quando vengono effettuate operazioni tra due array, numpy compara le shape dimensione per dimensione, dall'ultima
alla prima. Due dimensioni sono compatibili se:
<ul>
    <li>Sono uguali
    <li>Una di loro è uguale a uno
</ul>
Inoltre, le due shape non devono avere necessariamente lo stesso numero di dimensioni.

In [ ]:
mat1=np.array([[[1,3,5],[7,6,2]],[[6,5,2],[8,9,9]]])
mat2=np.array([[2,1,3],[7,6,2]])
print("mat1 shape",mat1.shape)
print("mat2 shape",mat2.shape)
print()
print("mat1\n",mat1)
print()
print("mat2\n",mat2)
print()
print("mat1*Mat2\n",mat1*mat2)

Il prodotto tra i due tensori è stato effettuato moltiplicando le matrici bidimensionali <code>mat1[0,...]</code> e <code>mat1[1,...]</code> per <code>mat2</code>. Ciò è equivalente a ripetere gli elementi di <code>mat2</code> lungo la dimensione mancante ed effettuare un prodotto punto a punto tra <code>mat1</code> e la versione adattata di <code>mat2</code>.

## - NumPy - FINE 